name: PHPUnit

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, json, dom, gd
          ini-values: post_max_size=256M, max_execution_time=180

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Zip
        uses: papeloto/action-zip@v1
        with:
          files: .
          dest: pars-admin.zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pars-admin
          path: pars-admin.zip
